-- AlterEnum (35. tur — Türkiye niş & yeni platformlar)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BAYMIO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'OTTOPLUS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KADIN_CLUB';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'VAKKO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BEYMEN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'NETWORK';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'COLINS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'US_POLO_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TWIST';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CEPTE_SOK';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ROSSMANN_ONLINE';
