-- AlterEnum (11. tur — Türk gıda marketleri, B2B/toptan, özel kanal platformları)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MIGROS_SANAL';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CARREFOURSA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BIM_ONLINE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SOK_MARKET';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TAZE_DIREKT';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GORILLAS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'INSTACART';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ALIBABA_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TRENDYOL_MILLA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SAHIBINDEN_PREMIUM';
