-- AlterEnum (34. tur — Latin Amerika, Kanada/Meksika)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SHOPEE_BR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CASAS_BAHIA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SUBMARINO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'RIPLEY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'COSTCO_CA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'HUDSONS_BAY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LIVERPOOL_MX';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'COPPEL';
