-- AlterEnum (30. tur — fintech, ödeme, sosyal ticaret, abonelik)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SQUARE_ONLINE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CLOVER';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'VENMO_BUSINESS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AFTERPAY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KLARNA_MERCHANT';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PAPARA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TOSLA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'OKX_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PARIBU';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BEREAL_SHOP';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'THREADS_SHOP';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'X_SHOPPING';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GUMROAD';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PATREON';
