-- AlterEnum (18. tur — Latin Amerika, Güneydoğu Asya, Türkiye marketplace)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AMERICANAS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MAGALU';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LINIO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'FALABELLA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GRAB_MART';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GOTO_BUSINESS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CENTRAL_ONLINE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AKULAKU';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'HIZLIRESMI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TICIMAX_MP';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'IKAS_MP';
