-- AlterEnum (15. tur — Avrupa B2C & outlet pazaryerleri)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ASOS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'VINTED';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SHEIN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ABOUT_YOU';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MIINTO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'JOOM';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'WISH';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'FRUUGO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ONBUY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TIKLADO';
