packages:
  - 'apps/*'
  - 'packages/*'
  - 'desktop'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - prisma

