-- AlterEnum (22. tur — İskandinav, Doğu Avrupa, Orta Doğu)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CDON';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ELLOS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'DUSTIN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KOMPLETT';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'POWER_DK';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CENEO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'HEUREKA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'OLX';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MUMZWORLD';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BOUTIQAAT';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AWOK';
