-- AlterEnum: Kargo sağlayıcıları — 3. tur (uluslararası + Türkiye)
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'TNT';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'GLS';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'DPD';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'HERMES';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'POSTNL';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'DHL_PARCEL';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'BRINGO';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'CEVA';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'NART_KARGO';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'KOLAY_GELSIN';
