-- AlterEnum (28. tur — oyun, dijital, moda secondhand global, spor, Türk niş)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'G2A';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KINGUIN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ENEBA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GAMEFLIP';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'DLGAMER';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MERCARI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TRADESY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'STOCKX';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GYMSHARK';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'DECATHLON_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'INTERSPORT_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SPORTIVE_TR';
