-- AlterEnum (10. tur — Kuzey Amerika, Avrupa perakende, Orta Doğu ek)
-- Önceki migration'larda eklenmiş değerler için idempotent (IF NOT EXISTS)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'WALMART';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TARGET_PLUS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BESTBUY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'WAYFAIR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'OVERSTOCK';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'FNAC';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LAREDOUTE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SPARTOO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MANOMANO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'VEEPEE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TRENDYOL_INT';
