-- AlterEnum (17. tur — Amazon global, Orta Asya, Güney Asya)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AMAZON_UK';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AMAZON_DE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AMAZON_FR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AMAZON_CA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AMAZON_JP';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KASPI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'UZUM';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'JIOMART';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'NOON_SA';
