/** Yaygın il adları → Yurtiçi / MNG şehir kodu (plaka) */
const CITY_CODE_BY_NAME: Record<string, string> = {
  adana: '01',
  adıyaman: '02',
  adiyaman: '02',
  afyon: '03',
  afyonkarahisar: '03',
  ağrı: '04',
  agri: '04',
  amasya: '05',
  ankara: '06',
  antalya: '07',
  artvin: '08',
  aydın: '09',
  aydin: '09',
  balıkesir: '10',
  balikesir: '10',
  bilecik: '11',
  bingöl: '12',
  bingol: '12',
  bitlis: '13',
  bolu: '14',
  burdur: '15',
  bursa: '16',
  çanakkale: '17',
  canakkale: '17',
  çankırı: '18',
  cankiri: '18',
  çorum: '19',
  corum: '19',
  denizli: '20',
  diyarbakır: '21',
  diyarbakir: '21',
  edirne: '22',
  elazığ: '23',
  elazig: '23',
  erzincan: '24',
  erzurum: '25',
  eskişehir: '26',
  eskisehir: '26',
  gaziantep: '27',
  giresun: '28',
  gümüşhane: '29',
  gumushane: '29',
  hakkari: '30',
  hatay: '31',
  ısparta: '32',
  isparta: '32',
  mersin: '33',
  istanbul: '34',
  izmir: '35',
  kars: '36',
  kastamonu: '37',
  kayseri: '38',
  kırklareli: '39',
  kirklareli: '39',
  kırşehir: '40',
  kirsehir: '40',
  kocaeli: '41',
  konya: '42',
  kütahya: '43',
  kutahya: '43',
  malatya: '44',
  manisa: '45',
  kahramanmaraş: '46',
  kahramanmaras: '46',
  mardin: '47',
  muğla: '48',
  mugla: '48',
  muş: '49',
  mus: '49',
  nevşehir: '50',
  nevsehir: '50',
  niğde: '51',
  nigde: '51',
  ordu: '52',
  rize: '53',
  sakarya: '54',
  samsun: '55',
  siirt: '56',
  sinop: '57',
  sivas: '58',
  tekirdağ: '59',
  tekirdag: '59',
  tokat: '60',
  trabzon: '61',
  tunceli: '62',
  şanlıurfa: '63',
  sanliurfa: '63',
  uşak: '64',
  usak: '64',
  van: '65',
  yozgat: '66',
  zonguldak: '67',
  aksaray: '68',
  bayburt: '69',
  karaman: '70',
  kırıkkale: '71',
  kirikkale: '71',
  batman: '72',
  şırnak: '73',
  sirnak: '73',
  bartın: '74',
  bartin: '74',
  ardahan: '75',
  ığdır: '76',
  igdir: '76',
  yalova: '77',
  karabük: '78',
  karabuk: '78',
  kilis: '79',
  osmaniye: '80',
  düzce: '81',
  duzce: '81',
};

export function resolveTurkishCityCode(city: string, fallback = '34'): string {
  const normalized = city
    .trim()
    .toLocaleLowerCase('tr-TR')
    .normalize('NFD')
    .replace(/\p{M}/gu, '');
  if (/^\d{1,2}$/.test(normalized)) {
    return normalized.padStart(2, '0');
  }
  const direct = CITY_CODE_BY_NAME[normalized];
  if (direct) {
    return direct;
  }
  for (const [name, code] of Object.entries(CITY_CODE_BY_NAME)) {
    if (normalized.includes(name) || name.includes(normalized)) {
      return code;
    }
  }
  return fallback;
}
