-- AlterEnum (21. tur — sosyal/live commerce, Avrupa, Asya, Türkiye niche)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'YOUTUBE_SHOP';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SNAPCHAT_STORE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'WHATSAPP_COMMERCE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CARREFOUR_FR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CASINO_FR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LIDL';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ALDI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SHOPBACK';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'COUPANG';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'STREET11';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BULDUMBULDUM';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ALISVERIS_COM';
