-- AlterEnum (16. tur — Türkiye perakende & hızlı teslimat kanalları)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KOCTAS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'WATSONS_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MIGROS_HIZLI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GETIR_MARKET';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MEDIAMARKT_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TRENDYOL_SECOND_HAND';
