-- E-ticaret altyapısı enum değerleri — 3. tur
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'COMMERCEJS';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'CRYSTALLIZE';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'NACELLE';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'ELASTIC_PATH';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'VTEX';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'SHOPIFY_TR';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'PAZARYOLU';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'EPTTAVM';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'GITTIGIDIYOR_SHOP';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'BAGISTO';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'AIMEOS';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'REACTION_COMMERCE';
