-- AlterEnum (32. tur — Asya-Pasifik & Okyanusya)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MERCARI_JP';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'YAHOO_AUCTIONS_JP';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ZOZOTOWN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KAKAO_COMMERCE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SHOPEE_SG';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SHOPEE_TH';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LAZADA_MY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ZALORA_MY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PGMALL';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KOGAN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'THEMARKET_NZ';
