-- AlterEnum (20. tur — Türkiye yeni nesil + global sosyal commerce)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PAZAR365';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'DOPING';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'YARGICI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ADIDAS_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ZARA_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TIKTOK_SHOP';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PINTEREST';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'INSTAGRAM_SHOP';
