-- AlterEnum (24. tur — Afrika, Orta Doğu niş, Güneydoğu Asya tamamlama)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'JIJI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CHEKI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PAYSTACK_COMMERCE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'FLUTTERWAVE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'REEBELO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ZID';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SALLA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CAROUSELL';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'POMELO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BEAUTYMNL';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ZALORA_PH';
