-- AlterEnum (9. tur — Türk perakende / B2C: ev & yaşam, moda, kitap)
-- Önceki migration'larda eklenmiş değerler için idempotent (IF NOT EXISTS)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MODANISA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SEFAMERVE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LIDYANA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ADDAX';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'VIVENSE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CICEKSEPETI_EV';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'EVIDEA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PORLAND';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KITAPYURDU';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'DR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SPORTIVE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ENPARA';
