-- AlterEnum (40. tur — küresel e-ticaret, Asya, Türkiye niş tamamlama)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'JUMIA_GH';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'JUMIA_TN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CARREFOUR_SA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LULU_ONLINE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'VIRGIN_MEGASTORE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TOKOPEDIA_FLASH';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GRABMART';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GOFOOD';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PANDAMART';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AVANSAS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KUKLA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BEBEK_COM';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TOYZZ_SHOP';
