-- AlterEnum (12. tur — headless e-ticaret, ödeme altyapısı, lojistik, bulut ERP)
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'SHOPIROLL';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'MEDUSA';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'VENDURE';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'SALEOR';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'IYZICO';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'STRIPE';

ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'NETLOG';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'HOROZ';

ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'BIZIM_MUHASEBE';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'LOGO_CLOUD';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'FINANS_MUHASEBE';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'MIKRO_BULUT';
