-- AlterEnum: Kargo sağlayıcıları — 3. tur (Türkiye, Avrupa, Asya)
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'PACKUPP';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'GELAL';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'EKOL';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'KOLLAY';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'HERMES_DE';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'DPD_DE';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'CHRONOPOST';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'CORREOS_EXPRESS';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'BRT';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'JT_EXPRESS';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'NINJA_VAN';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'KERRY_EXPRESS';
ALTER TYPE "CargoProvider" ADD VALUE IF NOT EXISTS 'FLASH_EXPRESS';
