-- AlterEnum
ALTER TYPE "EcommerceType" ADD VALUE 'MAGENTO';
ALTER TYPE "EcommerceType" ADD VALUE 'PRESTASHOP';
ALTER TYPE "EcommerceType" ADD VALUE 'OPENCART';
ALTER TYPE "EcommerceType" ADD VALUE 'FAPRIKA';
ALTER TYPE "EcommerceType" ADD VALUE 'UNIPOS';
ALTER TYPE "EcommerceType" ADD VALUE 'AKINON';
ALTER TYPE "EcommerceType" ADD VALUE 'IKAS';
