/**
 * Pazaryeri / ERP bağlantı formları için kimlik alanı tanımları.
 * Prisma `Marketplace` ve `ErpType` enum değerleriyle birebir anahtarlanır.
 */

export interface ConnectionFormFieldDef {
  key: string;
  label: string;
  placeholder?: string;
  type: 'text' | 'password' | 'url' | 'number';
  required: boolean;
  hint?: string;
  defaultValue?: string;
}

export const MARKETPLACE_CONNECTION_FORM_FIELDS: Record<
  string,
  ConnectionFormFieldDef[]
> = {
  TRENDYOL: [
    {
      key: 'supplierId',
      label: 'Tedarikçi ID',
      type: 'text',
      required: true,
    },
    {
      key: 'apiKey',
      label: 'API Key',
      type: 'password',
      required: true,
    },
    {
      key: 'apiSecret',
      label: 'API Secret',
      type: 'password',
      required: true,
    },
  ],
  HEPSIBURADA: [
    { key: 'username', label: 'Kullanıcı Adı', type: 'text', required: true },
    { key: 'password', label: 'Şifre', type: 'password', required: true },
    { key: 'merchantId', label: 'Merchant ID', type: 'text', required: true },
  ],
  N11: [
    { key: 'apiKey', label: 'API Key', type: 'text', required: true },
    { key: 'apiSecret', label: 'API Secret', type: 'password', required: true },
  ],
  CICEKSEPETI: [
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    { key: 'sellerId', label: 'Satıcı ID', type: 'text', required: true },
  ],
  AMAZON_TR: [
    { key: 'sellerId', label: 'Satıcı ID', type: 'text', required: true },
    { key: 'accessKeyId', label: 'Access Key', type: 'text', required: true },
    {
      key: 'secretAccessKey',
      label: 'Secret Key',
      type: 'password',
      required: true,
    },
    {
      key: 'refreshToken',
      label: 'Refresh Token',
      type: 'password',
      required: true,
    },
    {
      key: 'marketplaceId',
      label: 'Marketplace ID',
      type: 'text',
      required: true,
      defaultValue: 'A33AVAJ2PDY3EV',
      hint: 'Türkiye için varsayılan: A33AVAJ2PDY3EV',
    },
  ],
  PTTAVM: [
    { key: 'username', label: 'Kullanıcı Adı', type: 'text', required: true },
    { key: 'password', label: 'Şifre', type: 'password', required: true },
    { key: 'storeId', label: 'Mağaza ID', type: 'text', required: true },
  ],
  PAZARAMA: [
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    { key: 'apiSecret', label: 'API Secret', type: 'password', required: true },
  ],
  GETIR: [
    { key: 'merchantId', label: 'Merchant ID', type: 'text', required: true },
    { key: 'secret', label: 'Secret Key', type: 'password', required: true },
  ],
  GRATIS: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  BOYNER: [
    { key: 'clientId', label: 'Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'Client Secret',
      type: 'password',
      required: true,
    },
  ],
  MORHIPO: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  DOLAP: [
    {
      key: 'accessToken',
      label: 'Access Token',
      type: 'password',
      required: true,
    },
  ],
  EBAY: [
    { key: 'clientId', label: 'Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'refreshToken',
      label: 'Refresh Token',
      type: 'password',
      required: true,
    },
  ],
  ETSY: [
    { key: 'apiKey', label: 'API Key', type: 'text', required: true },
    { key: 'apiSecret', label: 'API Secret', type: 'password', required: true },
    { key: 'shopId', label: 'Mağaza ID', type: 'text', required: true },
    {
      key: 'accessToken',
      label: 'Access Token',
      type: 'password',
      required: true,
    },
  ],
  TEMU: [
    { key: 'appKey', label: 'App Key', type: 'text', required: true },
    { key: 'appSecret', label: 'App Secret', type: 'password', required: true },
  ],
  SAHIBINDEN: [
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
  ],
  SAHIBINDEN_PRO: [
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    { key: 'apiSecret', label: 'API Secret', type: 'password', required: true },
  ],
  TSOFT: [
    {
      key: 'storeUrl',
      label: 'Mağaza URL',
      type: 'url',
      placeholder: 'https://magaza.example.com',
      required: true,
      hint: 'http:// veya https:// ile tam adres girin.',
    },
    { key: 'clientId', label: 'Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'Client Secret',
      type: 'password',
      required: true,
    },
  ],
  TICIMAX: [
    {
      key: 'storeUrl',
      label: 'Mağaza URL',
      type: 'url',
      placeholder: 'https://magaza.example.com',
      required: true,
      hint: 'http:// veya https:// ile tam adres girin.',
    },
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
  ],
  WOOCOMMERCE: [
    {
      key: 'siteUrl',
      label: 'Site URL',
      type: 'url',
      placeholder: 'https://magaza.example.com',
      required: true,
      hint: 'http:// veya https:// ile tam adres girin.',
    },
    { key: 'consumerKey', label: 'Consumer Key', type: 'text', required: true },
    {
      key: 'consumerSecret',
      label: 'Consumer Secret',
      type: 'password',
      required: true,
    },
  ],
  SHOPIFY: [
    {
      key: 'shopDomain',
      label: 'Mağaza Domain',
      type: 'text',
      placeholder: 'mystore.myshopify.com',
      required: true,
    },
    { key: 'apiKey', label: 'API Key', type: 'text', required: true },
    {
      key: 'apiSecret',
      label: 'API Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'accessToken',
      label: 'Access Token',
      type: 'password',
      required: true,
    },
  ],
  SHOPIVERSE: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  IDEASOFT: [
    {
      key: 'storeUrl',
      label: 'Mağaza URL',
      type: 'url',
      placeholder: 'https://magaza.example.com',
      required: true,
      hint: 'http:// veya https:// ile tam adres girin.',
    },
    { key: 'apiKey', label: 'API Key', type: 'text', required: true },
  ],
  ALLEGRO: [
    { key: 'clientId', label: 'Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'scope',
      label: 'OAuth Scope (opsiyonel)',
      type: 'text',
      required: false,
      hint: 'Boş bırakılırsa Allegro varsayılan client_credentials kapsamı kullanılır.',
    },
    {
      key: 'accessToken',
      label: 'Access Token (opsiyonel, önbellek)',
      type: 'password',
      required: false,
    },
    {
      key: 'currency',
      label: 'Para birimi (fiyat için)',
      type: 'text',
      required: false,
      defaultValue: 'PLN',
    },
  ],
  WILDBERRIES: [
    { key: 'apiKey', label: 'API Key (Authorization)', type: 'password', required: true },
    {
      key: 'warehouseId',
      label: 'Depo ID (stok için)',
      type: 'text',
      required: true,
    },
    {
      key: 'currencyId',
      label: 'Para birimi ID (fiyat, örn. 643)',
      type: 'text',
      required: false,
      defaultValue: '643',
    },
  ],
  OZON: [
    { key: 'clientId', label: 'Client-Id', type: 'text', required: true },
    { key: 'apiKey', label: 'Api-Key', type: 'password', required: true },
    {
      key: 'warehouseId',
      label: 'Depo ID (stok için, sayı)',
      type: 'text',
      required: true,
    },
  ],
  NOON: [{ key: 'apiKey', label: 'Api-Key', type: 'password', required: true }],
  AMAZON_EU: [
    { key: 'sellerId', label: 'Satıcı ID', type: 'text', required: true },
    { key: 'clientId', label: 'LWA Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'LWA Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'refreshToken',
      label: 'Refresh Token',
      type: 'password',
      required: true,
    },
    {
      key: 'marketplaceId',
      label: 'Marketplace ID (DE/FR/UK/IT/ES)',
      type: 'text',
      required: true,
      hint: 'Örn. DE: A1PA6795UKMFR9, UK: A1F83G8C2ARO7P',
    },
    {
      key: 'currency',
      label: 'Para birimi (opsiyonel, örn. EUR)',
      type: 'text',
      required: false,
    },
  ],
  CDISCOUNT: [
    {
      key: 'apiLogin',
      label: 'API Login',
      type: 'text',
      required: true,
    },
    {
      key: 'apiPassword',
      label: 'API Password',
      type: 'password',
      required: true,
    },
  ],
  KAUFLAND: [
    { key: 'accessKey', label: 'Access Key (Shop-Client-Key)', type: 'text', required: true },
    {
      key: 'secretKey',
      label: 'Secret Key',
      type: 'password',
      required: true,
    },
  ],
  TRENDYOL_GO: [
    {
      key: 'supplierId',
      label: 'Tedarikçi / Mağaza ID',
      type: 'text',
      required: false,
      hint: 'Aynı SKU için farklı kanal ayırımı varsa doldurun.',
    },
    { key: 'apiKey', label: 'API Key (Basic kullanıcı)', type: 'text', required: true },
    {
      key: 'apiSecret',
      label: 'API Secret (Basic şifre)',
      type: 'password',
      required: true,
    },
    {
      key: 'channelId',
      label: 'Satış kanalı ID (opsiyonel)',
      type: 'text',
      required: false,
      hint: 'Aynı SKU, farklı kanal stokları için platform dokümantasyonuna göre.',
    },
  ],
  BANABI: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  A101: [
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    { key: 'merchantId', label: 'Merchant ID', type: 'text', required: true },
  ],
  ELEKTRA: [
    {
      key: 'accessToken',
      label: 'Bearer Token',
      type: 'password',
      required: true,
    },
  ],
  ARCELIK: [
    { key: 'clientId', label: 'OAuth2 Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'OAuth2 Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'accessToken',
      label: 'Access Token (opsiyonel, sabit token)',
      type: 'password',
      required: false,
      hint: 'Doluysa client credentials yerine doğrudan kullanılır.',
    },
  ],
  VESTEL: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  BIMAKILLI: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  MIGROSHEMEN: [
    {
      key: 'accessToken',
      label: 'Bearer Token',
      type: 'password',
      required: true,
    },
  ],
  ROBOMARKT: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  SHOPIGO: [
    {
      key: 'accessToken',
      label: 'Bearer Token',
      type: 'password',
      required: true,
    },
  ],
  YEMEKSEPETI: [
    {
      key: 'clientId',
      label: 'OAuth2 Client ID',
      type: 'text',
      required: false,
      hint: 'Access Token yoksa client credentials ile zorunludur.',
    },
    {
      key: 'clientSecret',
      label: 'OAuth2 Client Secret',
      type: 'password',
      required: false,
      hint: 'Access Token yoksa client credentials ile zorunludur.',
    },
    {
      key: 'accessToken',
      label: 'Access Token (opsiyonel, sabit token)',
      type: 'password',
      required: false,
      hint: 'Doluysa client credentials yerine doğrudan kullanılır.',
    },
    {
      key: 'merchantId',
      label: 'Merchant ID (opsiyonel)',
      type: 'text',
      required: false,
    },
  ],
  GETIR_YEMEK: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  GETIR_FOOD: [
    {
      key: 'accessToken',
      label: 'Bearer Token',
      type: 'password',
      required: true,
    },
  ],
  TRENDYOL_YEMEK: [
    {
      key: 'apiKey',
      label: 'API Key (Basic kullanıcı)',
      type: 'text',
      required: true,
    },
    {
      key: 'apiSecret',
      label: 'API Secret (Basic şifre)',
      type: 'password',
      required: true,
    },
    {
      key: 'supplierId',
      label: 'Tedarikçi ID',
      type: 'text',
      required: true,
      hint: 'Trendyol Food API yolu için zorunlu.',
    },
  ],
  FUUDY: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  MODANISA: [
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    { key: 'sellerId', label: 'Satıcı ID', type: 'text', required: true },
  ],
  SEFAMERVE: [
    {
      key: 'accessToken',
      label: 'Bearer Token',
      type: 'password',
      required: true,
    },
  ],
  LIDYANA: [
    {
      key: 'accessToken',
      label: 'Bearer Token',
      type: 'password',
      required: true,
    },
  ],
  ADDAX: [
    {
      key: 'accessToken',
      label: 'Bearer Token',
      type: 'password',
      required: true,
    },
  ],
  VIVENSE: [
    { key: 'clientId', label: 'OAuth2 Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'OAuth2 Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'accessToken',
      label: 'Access Token (Bearer)',
      type: 'password',
      required: true,
      hint: 'OAuth2 yetkilendirme akışıyla alınan token.',
    },
  ],
  CICEKSEPETI_EV: [
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    { key: 'sellerId', label: 'Satıcı ID', type: 'text', required: true },
    {
      key: 'categoryId',
      label: 'Ev & yaşam kategori / kanal ID',
      type: 'text',
      required: false,
      hint: 'X-Category-Id header değeri; boş bırakılırsa ev-yasam kullanılır.',
    },
  ],
  EVIDEA: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  PORLAND: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  ALIBABA: [
    { key: 'appKey', label: 'App Key', type: 'text', required: true },
    { key: 'appSecret', label: 'App Secret', type: 'password', required: true },
    {
      key: 'sessionKey',
      label: 'Session Key (OAuth2)',
      type: 'password',
      required: true,
    },
  ],
  MADEINCHINA: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  EXPORTIFY: [
    {
      key: 'accessToken',
      label: 'Bearer Token',
      type: 'password',
      required: true,
    },
  ],
  GITTIGIDIYOR: [
    { key: 'clientId', label: 'Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'refreshToken',
      label: 'Refresh Token',
      type: 'password',
      required: true,
    },
    {
      key: 'accessToken',
      label: 'Access Token (opsiyonel)',
      type: 'password',
      required: false,
    },
  ],
  KITAPYURDU: [
    { key: 'username', label: 'Kullanıcı Adı', type: 'text', required: true },
    { key: 'password', label: 'Şifre', type: 'password', required: true },
  ],
  DR: [
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    { key: 'apiSecret', label: 'API Secret', type: 'password', required: true },
  ],
  SPORTIVE: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  ENPARA: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  LAZADA: [
    { key: 'appKey', label: 'App Key', type: 'text', required: true },
    {
      key: 'accessToken',
      label: 'Access Token',
      type: 'password',
      required: true,
    },
  ],
  LETGO: [
    {
      key: 'accessToken',
      label: 'Access Token (OAuth2 Bearer)',
      type: 'password',
      required: true,
    },
  ],
  SHOPEE: [
    { key: 'partnerId', label: 'Partner ID', type: 'text', required: true },
    {
      key: 'partnerKey',
      label: 'Partner Key (gizli)',
      type: 'password',
      required: true,
    },
    {
      key: 'accessToken',
      label: 'Access Token',
      type: 'password',
      required: true,
    },
    { key: 'shopId', label: 'Shop ID', type: 'text', required: true },
  ],
  TOKOPEDIA: [
    { key: 'clientId', label: 'Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'accessToken',
      label: 'Access Token (Bearer)',
      type: 'password',
      required: true,
      hint: 'OAuth2 client credentials ile alınan token.',
    },
  ],
  MEESHO: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  OTTO: [
    { key: 'clientId', label: 'OAuth2 Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'OAuth2 Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'oauthTokenUrl',
      label: 'Token URL (opsiyonel)',
      type: 'url',
      required: false,
      hint: 'Boşsa Otto varsayılan token uç noktası kullanılır.',
    },
  ],
  ZALANDO: [
    { key: 'clientId', label: 'OAuth2 Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'OAuth2 Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'oauthTokenUrl',
      label: 'Token URL (opsiyonel)',
      type: 'url',
      required: false,
      hint: 'Boşsa Zalando merchant varsayılan token yolu kullanılır.',
    },
  ],
  BOLCOM: [
    {
      key: 'clientId',
      label: 'API Key (Client ID)',
      type: 'text',
      required: true,
    },
    {
      key: 'clientSecret',
      label: 'API Secret',
      type: 'password',
      required: true,
    },
  ],
  EMAG: [
    { key: 'username', label: 'Kullanıcı Adı', type: 'text', required: true },
    { key: 'password', label: 'Şifre', type: 'password', required: true },
  ],
  IDEALO: [
    { key: 'clientId', label: 'OAuth2 Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'OAuth2 Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'oauthTokenUrl',
      label: 'Token URL (opsiyonel)',
      type: 'url',
      required: false,
    },
  ],
  REALDE: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  ZARA: [
    { key: 'clientId', label: 'OAuth2 Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'OAuth2 Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'oauthTokenUrl',
      label: 'Token URL (opsiyonel)',
      type: 'url',
      required: false,
    },
  ],
  DECATHLON: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  HEPSIBURADA_PREMIUM: [
    { key: 'username', label: 'Kullanıcı Adı', type: 'text', required: true },
    { key: 'password', label: 'Şifre', type: 'password', required: true },
    { key: 'merchantId', label: 'Merchant ID', type: 'text', required: true },
    {
      key: 'merchantTier',
      label: 'Tier değeri',
      type: 'text',
      required: false,
      defaultValue: 'PREMIUM',
      hint: 'Varsayılan: PREMIUM. Özel başlık adı için tierHeaderName kullanın.',
    },
    {
      key: 'tierHeaderName',
      label: 'Tier HTTP başlık adı (opsiyonel)',
      type: 'text',
      required: false,
      defaultValue: 'X-Merchant-Tier',
    },
  ],
  TRENDYOL_PREMIUM: [
    { key: 'sellerId', label: 'Satıcı ID', type: 'text', required: true },
    { key: 'apiKey', label: 'API Key', type: 'text', required: true },
    {
      key: 'apiSecret',
      label: 'API Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'premiumFlag',
      label: 'Premium bayrağı (X-Premium-Seller)',
      type: 'text',
      required: false,
      defaultValue: 'true',
    },
  ],
  PAZARAMA_PREMIUM: [
    { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    { key: 'apiSecret', label: 'API Secret', type: 'password', required: true },
    {
      key: 'merchantTier',
      label: 'Kurumsal / tier değeri',
      type: 'text',
      required: false,
      defaultValue: 'PREMIUM',
    },
    {
      key: 'supplierId',
      label: 'Tedarikçi ID (opsiyonel)',
      type: 'text',
      required: false,
    },
  ],
  N11_PRO: [
    { key: 'apiKey', label: 'API Key', type: 'text', required: true },
    { key: 'apiSecret', label: 'API Secret', type: 'password', required: true },
  ],
  AMAZON_AE: [
    { key: 'sellerId', label: 'Satıcı ID', type: 'text', required: true },
    { key: 'clientId', label: 'LWA Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'LWA Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'refreshToken',
      label: 'Refresh Token',
      type: 'password',
      required: true,
    },
    {
      key: 'marketplaceId',
      label: 'Marketplace ID (amazon.ae)',
      type: 'text',
      required: true,
      defaultValue: 'A2VIGQ35RCS4UG',
      hint: 'BAE (amazon.ae) varsayılan: A2VIGQ35RCS4UG',
    },
    {
      key: 'currency',
      label: 'Para birimi (opsiyonel, örn. AED)',
      type: 'text',
      required: false,
    },
  ],
  NAMSHI: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  CARREFOUR_ME: [
    { key: 'clientId', label: 'OAuth2 Client ID', type: 'text', required: true },
    {
      key: 'clientSecret',
      label: 'OAuth2 Client Secret',
      type: 'password',
      required: true,
    },
    {
      key: 'oauthTokenUrl',
      label: 'Token URL (opsiyonel)',
      type: 'url',
      required: false,
      hint: 'Boşsa Carrefour ME varsayılan token uç noktası kullanılır.',
    },
  ],
  JUMIA: [
    { key: 'apiKey', label: 'API Key', type: 'text', required: true },
    { key: 'apiSecret', label: 'API Secret', type: 'password', required: true },
  ],
  DARAZ: [
    { key: 'appKey', label: 'App Key', type: 'text', required: true },
    {
      key: 'accessToken',
      label: 'Access Token',
      type: 'password',
      required: true,
    },
  ],
  FLIPKART: [
    {
      key: 'accessToken',
      label: 'Access Token (OAuth2 Bearer)',
      type: 'password',
      required: true,
    },
    {
      key: 'clientId',
      label: 'Client ID (opsiyonel)',
      type: 'text',
      required: false,
    },
  ],
  SNAPDEAL: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  MYNTRA: [
    {
      key: 'accessToken',
      label: 'Access Token (OAuth2 Bearer)',
      type: 'password',
      required: true,
    },
  ],
  RAKUTEN: [
    { key: 'licenseKey', label: 'License Key', type: 'text', required: true },
    {
      key: 'serviceSecret',
      label: 'Service Secret',
      type: 'password',
      required: true,
    },
  ],
  QOO10: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
  LAZADA_PH: [
    { key: 'appKey', label: 'App Key', type: 'text', required: true },
    {
      key: 'accessToken',
      label: 'Access Token',
      type: 'password',
      required: true,
    },
  ],
  MERCADOLIBRE: [
    {
      key: 'accessToken',
      label: 'Access Token (OAuth2 Bearer)',
      type: 'password',
      required: true,
    },
    {
      key: 'clientId',
      label: 'Uygulama Client ID (opsiyonel)',
      type: 'text',
      required: false,
    },
  ],
};

export const ERP_CONNECTION_FORM_FIELDS: Record<string, ConnectionFormFieldDef[]> =
  {
    BIZIMHESAP: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    ],
    PARASUT: [
      { key: 'clientId', label: 'Client ID', type: 'text', required: true },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
      { key: 'companyId', label: 'Şirket ID', type: 'text', required: true },
    ],
    LOGO: [
      {
        key: 'baseUrl',
        label: 'Sunucu URL',
        type: 'url',
        placeholder: 'http://192.168.1.10:8080',
        required: true,
        hint: 'Yerel sunucu için http:// veya https:// kullanabilirsiniz.',
      },
      { key: 'username', label: 'Kullanıcı', type: 'text', required: true },
      { key: 'password', label: 'Şifre', type: 'password', required: true },
      { key: 'firmNo', label: 'Firma No', type: 'text', required: true },
    ],
    MIKRO: [
      {
        key: 'baseUrl',
        label: 'Sunucu URL',
        type: 'url',
        placeholder: 'http://192.168.1.10',
        required: true,
        hint: 'http:// veya https:// ile tam adres girin.',
      },
      { key: 'username', label: 'Kullanıcı', type: 'text', required: true },
      { key: 'password', label: 'Şifre', type: 'password', required: true },
      { key: 'dbName', label: 'Veritabanı', type: 'text', required: true },
    ],
    NETSIS: [
      {
        key: 'baseUrl',
        label: 'Sunucu URL',
        type: 'url',
        placeholder: 'http://192.168.1.10',
        required: true,
        hint: 'http:// veya https:// ile tam adres girin.',
      },
      { key: 'username', label: 'Kullanıcı', type: 'text', required: true },
      { key: 'password', label: 'Şifre', type: 'password', required: true },
    ],
    LUCA: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true },
      { key: 'companyNo', label: 'Şirket No', type: 'text', required: true },
    ],
    ETA: [
      {
        key: 'baseUrl',
        label: 'Sunucu URL',
        type: 'url',
        placeholder: 'http://192.168.1.10:8080/eta/api veya .../etav8api',
        required: false,
        hint: 'ETA V8 için .../etav8api veya etaVersion=v8 + host kullanın.',
      },
      {
        key: 'host',
        label: 'Sunucu (baseUrl boşsa)',
        type: 'text',
        placeholder: '192.168.1.10',
        required: false,
      },
      {
        key: 'port',
        label: 'Port',
        type: 'number',
        required: false,
        defaultValue: '80',
      },
      {
        key: 'useHttps',
        label: 'HTTPS (true/false)',
        type: 'text',
        required: false,
        defaultValue: 'false',
      },
      {
        key: 'etaVersion',
        label: 'ETA sürümü',
        type: 'text',
        required: false,
        defaultValue: 'legacy',
        hint: 'V8 REST için: v8',
      },
      {
        key: 'apiToken',
        label: 'API token (ETA V8)',
        type: 'password',
        required: false,
        hint: 'V8 modunda kullanıcı yerine statik token kullanılabilir.',
      },
      { key: 'username', label: 'Kullanıcı', type: 'text', required: false },
      { key: 'password', label: 'Şifre', type: 'password', required: false },
    ],
    KOLAYBI: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    ],
    ZIRVE: [
      {
        key: 'baseUrl',
        label: 'REST köprü URL (opsiyonel)',
        type: 'url',
        placeholder: 'http://192.168.1.10:8080/zirveapi',
        required: false,
        hint: 'Boşsa host+port+/zirveapi kullanılır.',
      },
      {
        key: 'host',
        label: 'Sunucu',
        type: 'text',
        placeholder: '192.168.1.10',
        required: true,
      },
      {
        key: 'port',
        label: 'Port',
        type: 'number',
        required: true,
        defaultValue: '8080',
      },
      {
        key: 'firmNo',
        label: 'Firma no',
        type: 'text',
        required: true,
        defaultValue: '1',
        hint: 'stokkart listesi için kullanılır.',
      },
      { key: 'username', label: 'Kullanıcı', type: 'text', required: true },
      { key: 'password', label: 'Şifre', type: 'password', required: true },
      {
        key: 'token',
        label: 'Bearer token (opsiyonel)',
        type: 'password',
        required: false,
        hint: 'Doluysa kullanıcı/şifre ile oturum açılmaz.',
      },
    ],
    NEBIM: [
      {
        key: 'baseUrl',
        label: 'Tam kök URL (opsiyonel)',
        type: 'url',
        placeholder: 'https://sunucu:443/NebimV3WS veya .../nebimv3/api',
        required: false,
        hint: 'Nebim V3 REST için .../nebimv3/api veya nebimApi=v3_rest.',
      },
      {
        key: 'host',
        label: 'Sunucu',
        type: 'text',
        placeholder: '192.168.1.10',
        required: true,
      },
      {
        key: 'port',
        label: 'Port (V3 REST)',
        type: 'number',
        required: false,
        defaultValue: '8080',
      },
      {
        key: 'useHttps',
        label: 'HTTPS (true/false)',
        type: 'text',
        required: false,
        defaultValue: 'false',
      },
      {
        key: 'nebimApi',
        label: 'API modu',
        type: 'text',
        required: false,
        defaultValue: 'integrator',
        hint: 'Nebim V3 REST için: v3_rest',
      },
      { key: 'username', label: 'Kullanıcı', type: 'text', required: true },
      { key: 'password', label: 'Şifre', type: 'password', required: true },
    ],
    EBA: [
      { key: 'clientId', label: 'Client ID', type: 'text', required: true },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
      {
        key: 'apiBaseUrl',
        label: 'API URL',
        type: 'url',
        placeholder: 'https://api.ornek.com',
        required: true,
        hint: 'http:// veya https:// ile tam adres girin.',
      },
    ],
    SAP_B1: [
      {
        key: 'baseUrl',
        label: 'Service Layer URL (opsiyonel)',
        type: 'url',
        placeholder: 'https://192.168.1.10:50000/b1s/v1',
        required: false,
        hint: 'Doluysa host/port yerine doğrudan kullanılır. Boşsa aşağıdaki sunucu ve port ile oluşturulur.',
      },
      {
        key: 'host',
        label: 'Sunucu',
        type: 'text',
        placeholder: '192.168.1.10',
        required: false,
        hint: 'baseUrl boşsa zorunludur.',
      },
      {
        key: 'port',
        label: 'Port',
        type: 'number',
        required: false,
        defaultValue: '50000',
        hint: 'baseUrl doluysa yok sayılabilir.',
      },
      {
        key: 'useHttps',
        label: 'HTTPS (true/false)',
        type: 'text',
        required: false,
        defaultValue: 'true',
        hint: 'Varsayılan: true. Sadece HTTP için false yazın.',
      },
      { key: 'username', label: 'Kullanıcı', type: 'text', required: true },
      { key: 'password', label: 'Şifre', type: 'password', required: true },
      { key: 'companyDB', label: 'Şirket DB', type: 'text', required: true },
    ],
    ISNET: [
      {
        key: 'baseUrl',
        label: 'API kök URL',
        type: 'url',
        placeholder: 'https://dev.isnetworld.com',
        required: false,
        hint: 'Boşsa aşağıdaki sunucu ile https:// veya http:// oluşturulur.',
      },
      {
        key: 'host',
        label: 'Sunucu (baseUrl boşsa)',
        type: 'text',
        placeholder: 'dev.isnetworld.com',
        required: false,
      },
      {
        key: 'useHttps',
        label: 'HTTPS (true/false)',
        type: 'text',
        required: false,
        defaultValue: 'true',
      },
      { key: 'username', label: 'Kullanıcı', type: 'text', required: true },
      { key: 'password', label: 'Şifre', type: 'password', required: true },
      { key: 'companyCode', label: 'Şirket kodu', type: 'text', required: true },
      {
        key: 'apiKey',
        label: 'API Key (eski JSON köprü, opsiyonel)',
        type: 'password',
        required: false,
        hint: 'XML servis yerine özel JSON köprü kullanıyorsanız doldurun.',
      },
    ],
    MYSOFT: [
      {
        key: 'baseUrl',
        label: 'API kök URL (opsiyonel)',
        type: 'url',
        placeholder: 'https://api.mysoft.com.tr',
        required: false,
        hint: 'Boşsa https://api.mysoft.com.tr kullanılır.',
      },
      { key: 'username', label: 'Kullanıcı adı', type: 'text', required: true },
      { key: 'password', label: 'Şifre', type: 'password', required: true },
      { key: 'licenseKey', label: 'Lisans anahtarı', type: 'password', required: true },
    ],
    PROTEL: [
      {
        key: 'baseUrl',
        label: 'PMS API kök URL (opsiyonel)',
        type: 'url',
        placeholder: 'https://api.protel.com.tr',
        required: false,
        hint: 'Boşsa https://api.protel.com.tr kullanılır.',
      },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    ],
    SIMPRA: [{ key: 'apiKey', label: 'API Key', type: 'password', required: true }],
    LOGO_COMMERCE: [
      {
        key: 'baseUrl',
        label: 'Logo Go kök URL',
        type: 'url',
        placeholder: 'https://api.logo.com.tr',
        required: false,
        hint: 'Boşsa https://api.logo.com.tr kullanılır.',
      },
      { key: 'username', label: 'Kullanıcı', type: 'text', required: true },
      { key: 'password', label: 'Şifre', type: 'password', required: true },
      { key: 'firmNo', label: 'Firma No', type: 'text', required: true },
      { key: 'periodNo', label: 'Dönem No', type: 'text', required: true },
    ],
    TSOFT: [
      {
        key: 'storeUrl',
        label: 'Mağaza URL',
        type: 'url',
        placeholder: 'https://magaza.example.com',
        required: true,
        hint: 'http:// veya https:// ile tam adres girin.',
      },
      { key: 'clientId', label: 'Client ID', type: 'text', required: true },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    TICIMAX: [
      {
        key: 'storeUrl',
        label: 'Mağaza URL',
        type: 'url',
        placeholder: 'https://magaza.example.com',
        required: true,
        hint: 'http:// veya https:// ile tam adres girin.',
      },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true },
    ],
  };

/** Prisma `Marketplace` enum sırasına yakın, UI listesi için */
export const MARKETPLACE_PLATFORM_IDS: string[] = [
  'TRENDYOL',
  'HEPSIBURADA',
  'N11',
  'CICEKSEPETI',
  'AMAZON_TR',
  'AMAZON_EU',
  'ALLEGRO',
  'WILDBERRIES',
  'OZON',
  'NOON',
  'CDISCOUNT',
  'KAUFLAND',
  'PTTAVM',
  'PAZARAMA',
  'GETIR',
  'GRATIS',
  'BOYNER',
  'MORHIPO',
  'DOLAP',
  'EBAY',
  'ETSY',
  'TEMU',
  'SAHIBINDEN',
  'TRENDYOL_GO',
  'BANABI',
  'A101',
  'ELEKTRA',
  'ARCELIK',
  'VESTEL',
  'BIMAKILLI',
  'MIGROSHEMEN',
  'ROBOMARKT',
  'SHOPIGO',
  'YEMEKSEPETI',
  'GETIR_FOOD',
  'GETIR_YEMEK',
  'TRENDYOL_YEMEK',
  'FUUDY',
  'MODANISA',
  'SEFAMERVE',
  'LIDYANA',
  'ADDAX',
  'VIVENSE',
  'CICEKSEPETI_EV',
  'EVIDEA',
  'PORLAND',
  'ALIBABA',
  'MADEINCHINA',
  'EXPORTIFY',
  'GITTIGIDIYOR',
  'KITAPYURDU',
  'DR',
  'SPORTIVE',
  'ENPARA',
  'LAZADA',
  'SHOPEE',
  'TOKOPEDIA',
  'MEESHO',
  'OTTO',
  'ZALANDO',
  'BOLCOM',
  'EMAG',
  'IDEALO',
  'REALDE',
  'ZARA',
  'DECATHLON',
  'HEPSIBURADA_PREMIUM',
  'TRENDYOL_PREMIUM',
  'PAZARAMA_PREMIUM',
  'N11_PRO',
  'AMAZON_AE',
  'NAMSHI',
  'CARREFOUR_ME',
  'JUMIA',
  'DARAZ',
  'FLIPKART',
  'SNAPDEAL',
  'MYNTRA',
  'RAKUTEN',
  'QOO10',
  'LAZADA_PH',
  'LETGO',
  'MERCADOLIBRE',
  'SAHIBINDEN_PRO',
  'SHOPIVERSE',
];

export const ECOMMERCE_MARKETPLACE_IDS: string[] = [
  'TSOFT',
  'TICIMAX',
  'WOOCOMMERCE',
  'SHOPIFY',
  'IDEASOFT',
  'SHOPIVERSE',
];

export const ERP_TYPE_IDS: string[] = [
  'BIZIMHESAP',
  'PARASUT',
  'LOGO',
  'MIKRO',
  'NETSIS',
  'LUCA',
  'ETA',
  'KOLAYBI',
  'ZIRVE',
  'NEBIM',
  'EBA',
  'SAP_B1',
  'ISNET',
  'MYSOFT',
  'PROTEL',
  'SIMPRA',
  'LOGO_COMMERCE',
  'TSOFT',
  'TICIMAX',
];

export function getMarketplaceFormFields(
  platform: string,
): ConnectionFormFieldDef[] {
  return MARKETPLACE_CONNECTION_FORM_FIELDS[platform] ?? [];
}

export function getErpFormFields(erpType: string): ConnectionFormFieldDef[] {
  return ERP_CONNECTION_FORM_FIELDS[erpType] ?? [];
}
