export interface PlatformDisplayMeta {
  label: string;
  logo: string;
  /** Tailwind renk adı — rozet / vurgu için */
  color: string;
}

export const MARKETPLACE_DISPLAY: Record<string, PlatformDisplayMeta> = {
  TRENDYOL: { label: 'Trendyol', logo: '🛍️', color: 'orange' },
  HEPSIBURADA: { label: 'Hepsiburada', logo: '🏪', color: 'amber' },
  N11: { label: 'N11', logo: '🔶', color: 'violet' },
  AMAZON_TR: { label: 'Amazon.com.tr', logo: '📦', color: 'amber' },
  AMAZON_EU: { label: 'Amazon Avrupa (SP-API)', logo: '📦', color: 'amber' },
  AMAZON_AE: { label: 'Amazon UAE (amazon.ae)', logo: '📦', color: 'amber' },
  AMAZON_UK: { label: 'Amazon UK (amazon.co.uk)', logo: '📦', color: 'amber' },
  AMAZON_DE: { label: 'Amazon DE (amazon.de)', logo: '📦', color: 'amber' },
  AMAZON_FR: { label: 'Amazon FR (amazon.fr)', logo: '📦', color: 'amber' },
  AMAZON_CA: { label: 'Amazon CA (amazon.ca)', logo: '📦', color: 'amber' },
  AMAZON_JP: { label: 'Amazon JP (amazon.co.jp)', logo: '📦', color: 'amber' },
  ALLEGRO: { label: 'Allegro', logo: '🇪🇺', color: 'orange' },
  WILDBERRIES: { label: 'Wildberries', logo: '🛒', color: 'violet' },
  OZON: { label: 'Ozon', logo: '🔵', color: 'blue' },
  NOON: { label: 'Noon', logo: '🌙', color: 'amber' },
  NOON_SA: { label: 'Noon Suudi Arabistan', logo: '🌙', color: 'amber' },
  KASPI: { label: 'Kaspi.kz', logo: '🇰🇿', color: 'red' },
  AMERICANAS: { label: 'Americanas', logo: '🇧🇷', color: 'red' },
  MAGALU: { label: 'Magazine Luiza', logo: '🇧🇷', color: 'blue' },
  LINIO: { label: 'Linio', logo: '🌎', color: 'sky' },
  FALABELLA: { label: 'Falabella', logo: '🇨🇱', color: 'green' },
  GRAB_MART: { label: 'Grab Mart', logo: '🛒', color: 'emerald' },
  GOTO_BUSINESS: { label: 'GoTo / Tokopedia Business', logo: '🇮🇩', color: 'green' },
  CENTRAL_ONLINE: { label: 'Central Online', logo: '🇹🇭', color: 'purple' },
  AKULAKU: { label: 'Akulaku', logo: '🇮🇩', color: 'orange' },
  HIZLIRESMI: { label: 'Hizliresmi.com', logo: '🏛️', color: 'slate' },
  TICIMAX_MP: { label: 'Ticimax Marketplace', logo: '🛒', color: 'teal' },
  IKAS_MP: { label: 'İkas Marketplace', logo: '🛍️', color: 'violet' },
  UZUM: { label: 'Uzum', logo: '🇺🇿', color: 'violet' },
  CDISCOUNT: { label: 'Cdiscount', logo: '🇫🇷', color: 'red' },
  KAUFLAND: { label: 'Kaufland', logo: '🏪', color: 'emerald' },
  CICEKSEPETI: { label: 'Çiçeksepeti', logo: '🌸', color: 'pink' },
  IDEASOFT: { label: 'İdeasoft', logo: '💡', color: 'sky' },
  PTTAVM: { label: 'PTT AVM', logo: '📬', color: 'blue' },
  PAZARAMA: { label: 'Pazarama', logo: '🛒', color: 'indigo' },
  TSOFT: { label: 'T-Soft', logo: '🏬', color: 'cyan' },
  TICIMAX: { label: 'Ticimax', logo: '🛒', color: 'teal' },
  WOOCOMMERCE: { label: 'WooCommerce', logo: '🟣', color: 'purple' },
  SHOPIFY: { label: 'Shopify', logo: '🛍️', color: 'emerald' },
  GETIR: { label: 'Getir', logo: '🟣', color: 'purple' },
  GRATIS: { label: 'Gratis', logo: '💄', color: 'rose' },
  BOYNER: { label: 'Boyner', logo: '👔', color: 'slate' },
  FLO: { label: 'Flo', logo: '👟', color: 'blue' },
  DEFACTO: { label: 'DeFacto', logo: '👕', color: 'slate' },
  LCWAIKIKI: { label: 'LC Waikiki', logo: '👔', color: 'indigo' },
  KOCTAS: { label: 'Koçtaş', logo: '🔨', color: 'orange' },
  HOUZZ: { label: 'Houzz', logo: '🏠', color: 'green' },
  MADE_COM: { label: 'Made.com', logo: '🛋️', color: 'slate' },
  ARTICLE: { label: 'Article', logo: '🪑', color: 'amber' },
  JOSS_MAIN: { label: 'Joss & Main', logo: '🏡', color: 'rose' },
  BIRCH_LANE: { label: 'Birch Lane', logo: '🌳', color: 'emerald' },
  PERIGOLD: { label: 'Perigold', logo: '✨', color: 'yellow' },
  KARACA: { label: 'Karaca', logo: '🍳', color: 'red' },
  MADAME_COCO: { label: 'Madame Coco', logo: '🛏️', color: 'pink' },
  ENGLISH_HOME: { label: 'English Home', logo: '🏠', color: 'blue' },
  LINENS_N_THINGS: { label: "Linens 'n Things", logo: '🛁', color: 'sky' },
  GARDENA: { label: 'Gardena', logo: '🌿', color: 'green' },
  OBI_TR: { label: 'Obi TR', logo: '🔧', color: 'orange' },
  BAUHAUS_TR: { label: 'Bauhaus TR', logo: '🏗️', color: 'blue' },
  WATSONS_TR: { label: 'Watsons TR', logo: '💄', color: 'green' },
  TEKNOSA: { label: 'Teknosa', logo: '📱', color: 'blue' },
  MEDIAMARKT_TR: { label: 'MediaMarkt TR', logo: '📺', color: 'red' },
  MIGROS_HIZLI: { label: 'Migros Hızlı', logo: '⚡', color: 'orange' },
  GETIR_MARKET: { label: 'Getir Market', logo: '🛒', color: 'purple' },
  MORHIPO: { label: 'Morhipo', logo: '👗', color: 'fuchsia' },
  DOLAP: { label: 'Dolap', logo: '👜', color: 'lime' },
  EBAY: { label: 'eBay', logo: '🌐', color: 'yellow' },
  ETSY: { label: 'Etsy', logo: '🧵', color: 'orange' },
  TEMU: { label: 'Temu', logo: '📦', color: 'red' },
  SAHIBINDEN: { label: 'Sahibinden', logo: '🏷️', color: 'yellow' },
  TRENDYOL_GO: { label: 'Trendyol GO', logo: '⚡', color: 'orange' },
  TRENDYOL_SECOND_HAND: { label: 'İkinci El Trendyol', logo: '♻️', color: 'emerald' },
  BANABI: { label: 'Banabi', logo: '🛒', color: 'red' },
  A101: { label: 'A101 Online', logo: '🏷️', color: 'red' },
  ELEKTRA: { label: 'Elektra', logo: '🔌', color: 'blue' },
  ARCELIK: { label: 'Arçelik D2C', logo: '🏠', color: 'sky' },
  VESTEL: { label: 'Vestel D2C', logo: '📺', color: 'slate' },
  BIMAKILLI: { label: 'Bim Akıllı', logo: '🥬', color: 'green' },
  MIGROSHEMEN: { label: 'Migros Hemen', logo: '🚀', color: 'orange' },
  ROBOMARKT: { label: 'Robomarkt', logo: '🤖', color: 'cyan' },
  SHOPIGO: { label: 'Shopigo', logo: '🛍️', color: 'violet' },
  YEMEKSEPETI: { label: 'Yemeksepeti Market', logo: '🛒', color: 'orange' },
  GETIR_FOOD: { label: 'Getir Yemek', logo: '🍔', color: 'purple' },
  TRENDYOL_YEMEK: { label: 'Trendyol Yemek', logo: '🍽️', color: 'orange' },
  FUUDY: { label: 'Fuudy', logo: '🥬', color: 'emerald' },
  MODANISA: { label: 'Modanisa', logo: '🧕', color: 'rose' },
  SEFAMERVE: { label: 'Sefamerve', logo: '👗', color: 'pink' },
  LIDYANA: { label: 'Lidyana', logo: '👚', color: 'fuchsia' },
  ADDAX: { label: 'Addax', logo: '👔', color: 'slate' },
  VIVENSE: { label: 'Vivense', logo: '🛋️', color: 'amber' },
  CICEKSEPETI_EV: { label: 'Çiçeksepeti Ev', logo: '🏠', color: 'pink' },
  EVIDEA: { label: 'Evidea', logo: '🏡', color: 'cyan' },
  PORLAND: { label: 'Porland', logo: '🍽️', color: 'stone' },
  ALIBABA: { label: 'Alibaba.com', logo: '🌏', color: 'orange' },
  MADEINCHINA: { label: 'Made-in-China', logo: '🏭', color: 'red' },
  EXPORTIFY: { label: 'Exportify', logo: '📤', color: 'sky' },
  GITTIGIDIYOR: { label: 'GittiGidiyor (arşiv)', logo: '📜', color: 'yellow' },
  KITAPYURDU: { label: 'Kitapyurdu', logo: '📚', color: 'amber' },
  DR: { label: 'D&R', logo: '🎵', color: 'rose' },
  SPORTIVE: { label: 'Sportive', logo: '⚽', color: 'emerald' },
  ENPARA: { label: 'Enpara Alışveriş', logo: '🏦', color: 'cyan' },
  LAZADA: { label: 'Lazada', logo: '🛒', color: 'blue' },
  SHOPEE: { label: 'Shopee', logo: '🧡', color: 'orange' },
  TOKOPEDIA: { label: 'Tokopedia', logo: '🇮🇩', color: 'green' },
  MEESHO: { label: 'Meesho', logo: '🇮🇳', color: 'fuchsia' },
  JIOMART: { label: 'JioMart', logo: '🇮🇳', color: 'blue' },
  OTTO: { label: 'Otto Market', logo: '🇩🇪', color: 'slate' },
  ZALANDO: { label: 'Zalando', logo: '👟', color: 'orange' },
  BOLCOM: { label: 'Bol.com', logo: '🇳🇱', color: 'blue' },
  EMAG: { label: 'eMAG', logo: '🇷🇴', color: 'red' },
  IDEALO: { label: 'Idealo', logo: '💶', color: 'emerald' },
  REALDE: { label: 'Real.de', logo: '🏪', color: 'red' },
  ZARA: { label: 'Zara Online', logo: '👗', color: 'stone' },
  DECATHLON: { label: 'Decathlon TR', logo: '⛷️', color: 'blue' },
  HEPSIBURADA_PREMIUM: { label: 'Hepsiburada Premium', logo: '⭐', color: 'amber' },
  TRENDYOL_PREMIUM: { label: 'Trendyol Premium', logo: '💎', color: 'orange' },
  PAZARAMA_PREMIUM: { label: 'Pazarama Premium', logo: '🏢', color: 'indigo' },
  N11_PRO: { label: 'N11 Pro', logo: '🔷', color: 'violet' },
  NAMSHI: { label: 'Namshi', logo: '👟', color: 'emerald' },
  CARREFOUR_ME: { label: 'Carrefour Orta Doğu', logo: '🛒', color: 'blue' },
  JUMIA: { label: 'Jumia', logo: '🌍', color: 'orange' },
  DARAZ: { label: 'Daraz', logo: '🇵🇰', color: 'green' },
  FLIPKART: { label: 'Flipkart', logo: '🇮🇳', color: 'blue' },
  SNAPDEAL: { label: 'Snapdeal', logo: '🛍️', color: 'red' },
  MYNTRA: { label: 'Myntra', logo: '👗', color: 'rose' },
  RAKUTEN: { label: 'Rakuten', logo: '🇯🇵', color: 'crimson' },
  QOO10: { label: 'Qoo10', logo: '🌏', color: 'violet' },
  LAZADA_PH: { label: 'Lazada Philippines', logo: '🇵🇭', color: 'blue' },
  MERCADOLIBRE: { label: 'Mercado Libre', logo: '🌎', color: 'yellow' },
  GETIR_YEMEK: { label: 'Getir Yemek (Partner API)', logo: '🍔', color: 'purple' },
  LETGO: { label: 'Letgo / OLX TR', logo: '♻️', color: 'emerald' },
  SAHIBINDEN_PRO: { label: 'Sahibinden Pro', logo: '🏢', color: 'yellow' },
  SHOPIVERSE: { label: 'Shopiverse', logo: '🛒', color: 'sky' },
  WALMART: { label: 'Walmart Marketplace', logo: '🔵', color: 'blue' },
  TARGET_PLUS: { label: 'Target Plus', logo: '🎯', color: 'red' },
  BESTBUY: { label: 'Best Buy Marketplace', logo: '💛', color: 'yellow' },
  WAYFAIR: { label: 'Wayfair', logo: '🛋️', color: 'purple' },
  OVERSTOCK: { label: 'Overstock', logo: '🏷️', color: 'red' },
  FNAC: { label: 'Fnac Marketplace', logo: '🇫🇷', color: 'orange' },
  LAREDOUTE: { label: 'La Redoute', logo: '👗', color: 'rose' },
  SPARTOO: { label: 'Spartoo', logo: '👟', color: 'blue' },
  MANOMANO: { label: 'ManoMano', logo: '🔧', color: 'green' },
  VEEPEE: { label: 'Veepee', logo: '💜', color: 'violet' },
  TRENDYOL_INT: { label: 'Trendyol International', logo: '🌍', color: 'orange' },
  MIGROS_SANAL: { label: 'Migros Sanal Market', logo: '🛒', color: 'orange' },
  CARREFOURSA: { label: 'CarrefourSA Online', logo: '🛒', color: 'blue' },
  BIM_ONLINE: { label: 'BIM Online', logo: '🏪', color: 'red' },
  SOK_MARKET: { label: 'ŞOK Market Online', logo: '🛍️', color: 'yellow' },
  TAZE_DIREKT: { label: 'Taze Direkt', logo: '🥬', color: 'green' },
  GORILLAS: { label: 'Gorillas', logo: '🦍', color: 'violet' },
  INSTACART: { label: 'Instacart Connect', logo: '🛒', color: 'green' },
  ALIBABA_TR: { label: 'Alibaba TR (1688)', logo: '🌏', color: 'orange' },
  TRENDYOL_MILLA: { label: 'Trendyol Milla', logo: '👗', color: 'rose' },
  SAHIBINDEN_PREMIUM: { label: 'Sahibinden Premium', logo: '⭐', color: 'yellow' },
  BUKALAPAK: { label: 'Bukalapak', logo: '🇮🇩', color: 'red' },
  JDID: { label: 'JD.ID', logo: '🛒', color: 'red' },
  BLIBLI: { label: 'Blibli', logo: '🇮🇩', color: 'blue' },
  TIKI: { label: 'Tiki', logo: '🇻🇳', color: 'blue' },
  SENDO: { label: 'Sendo', logo: '🇻🇳', color: 'red' },
  CATCH_AU: { label: 'Catch.com.au', logo: '🇦🇺', color: 'yellow' },
  MYDEAL: { label: 'MyDeal', logo: '🇦🇺', color: 'sky' },
  TRADEME: { label: 'Trade Me', logo: '🇳🇿', color: 'blue' },
  LAMODA: { label: 'Lamoda', logo: '🇷🇺', color: 'rose' },
  YANDEX_MARKET: { label: 'Yandex Market', logo: '🇷🇺', color: 'yellow' },
  MALL_CZ: { label: 'Mall.cz', logo: '🇨🇿', color: 'blue' },
  PIGU: { label: 'Pigu.lt', logo: '🇱🇹', color: 'amber' },
  PRICERUNNER: { label: 'Pricerunner', logo: '💶', color: 'emerald' },
  OUNASS: { label: 'Ounass', logo: '🇦🇪', color: 'stone' },
  SIVVI: { label: 'Sivvi', logo: '🇦🇪', color: 'rose' },
  IDEFIX: { label: 'Idefix', logo: '📚', color: 'orange' },
  PAZAR365: { label: 'Pazar365', logo: '🛍️', color: 'sky' },
  DOPING: { label: 'Doping Hafıza', logo: '📖', color: 'blue' },
  YARGICI: { label: 'Yargıcı', logo: '👔', color: 'slate' },
  ADIDAS_TR: { label: 'Adidas TR', logo: '👟', color: 'zinc' },
  ZARA_TR: { label: 'Zara TR', logo: '👗', color: 'stone' },
  TIKTOK_SHOP: { label: 'TikTok Shop', logo: '🎵', color: 'rose' },
  PINTEREST: { label: 'Pinterest Shopping', logo: '📌', color: 'red' },
  INSTAGRAM_SHOP: { label: 'Instagram Shopping', logo: '📸', color: 'fuchsia' },
  YOUTUBE_SHOP: { label: 'YouTube Shopping', logo: '▶️', color: 'red' },
  SNAPCHAT_STORE: { label: 'Snapchat Store', logo: '👻', color: 'yellow' },
  WHATSAPP_COMMERCE: { label: 'WhatsApp Business', logo: '💬', color: 'green' },
  CARREFOUR_FR: { label: 'Carrefour FR', logo: '🇫🇷', color: 'blue' },
  CASINO_FR: { label: 'Casino FR', logo: '🛒', color: 'orange' },
  LIDL: { label: 'Lidl Plus', logo: '🏪', color: 'blue' },
  ALDI: { label: 'Aldi', logo: '🛍️', color: 'orange' },
  SHOPBACK: { label: 'Shopback', logo: '💰', color: 'emerald' },
  COUPANG: { label: 'Coupang', logo: '🇰🇷', color: 'rose' },
  STREET11: { label: '11Street KR', logo: '1️⃣1️⃣', color: 'red' },
  BULDUMBULDUM: { label: 'Buldumbuldum', logo: '🏷️', color: 'amber' },
  ALISVERIS_COM: { label: 'Alışveriş.com', logo: '🔍', color: 'sky' },
  CDON: { label: 'CDON', logo: '🇸🇪', color: 'blue' },
  ELLOS: { label: 'Ellos', logo: '👗', color: 'rose' },
  DUSTIN: { label: 'Dustin', logo: '💻', color: 'slate' },
  KOMPLETT: { label: 'Komplett', logo: '🇳🇴', color: 'orange' },
  POWER_DK: { label: 'Power.dk', logo: '🇩🇰', color: 'red' },
  CENEO: { label: 'Ceneo', logo: '🇵🇱', color: 'orange' },
  HEUREKA: { label: 'Heureka', logo: '🇨🇿', color: 'blue' },
  OLX: { label: 'OLX', logo: '♻️', color: 'emerald' },
  MUMZWORLD: { label: 'Mumzworld', logo: '👶', color: 'pink' },
  BOUTIQAAT: { label: 'Boutiqaat', logo: '💄', color: 'violet' },
  AWOK: { label: 'Awok', logo: '🇦🇪', color: 'amber' },
  ALIBABA_B2B: { label: 'Alibaba B2B (1688)', logo: '🏭', color: 'orange' },
  GLOBAL_SOURCES: { label: 'Global Sources', logo: '🌐', color: 'blue' },
  DHGATE: { label: 'DHgate', logo: '🛒', color: 'yellow' },
  INDIAMART: { label: 'IndiaMart', logo: '🇮🇳', color: 'blue' },
  TRADEINDIA: { label: 'TradeIndia', logo: '🇮🇳', color: 'green' },
  EC21: { label: 'EC21', logo: '🇰🇷', color: 'sky' },
  TEDARIKCI: { label: 'Tedarikçi.com', logo: '📦', color: 'emerald' },
  BUYUK_MAGAZA: { label: 'Büyük Mağaza', logo: '🏬', color: 'violet' },
  TOPTANEVI: { label: 'Toptanevi', logo: '📦', color: 'indigo' },
  SAHIBINDEN_B2B: { label: 'Sahibinden B2B', logo: '🏢', color: 'yellow' },
  SPOCKET: { label: 'Spocket', logo: '🚀', color: 'purple' },
  OBERLO: { label: 'Oberlo', logo: '📦', color: 'green' },
  AUTODS: { label: 'AutoDS', logo: '⚡', color: 'sky' },
  DOBA: { label: 'Doba', logo: '📦', color: 'blue' },
};

export const ERP_DISPLAY: Record<string, PlatformDisplayMeta> = {
  BIZIMHESAP: { label: 'BizimHesap', logo: '📊', color: 'blue' },
  PARASUT: { label: 'Paraşüt', logo: '🧾', color: 'green' },
  LOGO: { label: 'Logo', logo: '🐯', color: 'orange' },
  MIKRO: { label: 'Mikro', logo: '⚙️', color: 'slate' },
  NETSIS: { label: 'Netsis', logo: '🏢', color: 'zinc' },
  LUCA: { label: 'Luca', logo: '☁️', color: 'sky' },
  ETA: { label: 'ETA', logo: '📒', color: 'stone' },
  KOLAYBI: { label: 'Kolaybi', logo: '☁️', color: 'cyan' },
  ZIRVE: { label: 'Zirve', logo: '📈', color: 'emerald' },
  NEBIM: { label: 'Nebim', logo: '🛍️', color: 'violet' },
  EBA: { label: 'eBA', logo: '📄', color: 'blue' },
  SAP_B1: { label: 'SAP Business One', logo: '🏢', color: 'blue' },
  ISNET: { label: 'İşnet', logo: '🔗', color: 'indigo' },
  MYSOFT: { label: 'Mysoft', logo: '☁️', color: 'blue' },
  PROTEL: { label: 'Protel PMS', logo: '🏨', color: 'cyan' },
  SIMPRA: { label: 'Simpra', logo: '🍽️', color: 'orange' },
  LOGO_COMMERCE: { label: 'Logo Commerce (Go!)', logo: '🐯', color: 'orange' },
  TSOFT: { label: 'T-Soft (ERP)', logo: '🏬', color: 'cyan' },
  TICIMAX: { label: 'Ticimax (ERP)', logo: '🛒', color: 'teal' },
};

export function getMarketplaceDisplay(platform: string): PlatformDisplayMeta {
  return (
    MARKETPLACE_DISPLAY[platform] ?? {
      label: platform,
      logo: '🔗',
      color: 'slate',
    }
  );
}

export function getErpDisplay(erpType: string): PlatformDisplayMeta {
  return (
    ERP_DISPLAY[erpType] ?? {
      label: erpType,
      logo: '🔗',
      color: 'slate',
    }
  );
}
