/** pathname → segment etiketi (statik rotalar) */
export const BREADCRUMB_LABELS: Record<string, string> = {
  '/dashboard': 'Gösterge Paneli',
  '/orders': 'Siparişler',
  '/shipping': 'Kargo',
  '/returns': 'İadeler',
  '/customers': 'Müşteriler',
  '/customers/segments': 'Segmentler',
  '/listings': 'İlanlar',
  '/products': 'Ürünler',
  '/products/import': 'İçe aktar',
  '/product-matching': 'Ürün Eşleştirme',
  '/categories': 'Kategoriler',
  '/products/count': 'Stok Sayımı',
  '/products/transfers': 'Stok Transferi',
  '/suppliers': 'Tedarikçiler',
  '/purchase-orders': 'Satın Alma Siparişleri',
  '/pricing': 'Fiyatlandırma',
  '/pricing/analysis': 'Fiyat analizi',
  '/campaigns': 'Kampanyalar',
  '/connections': 'Bağlantılar',
  '/connections/erp/setup': 'Kurulum',
  '/sync-logs': 'Sync Durumu',
  '/sync/history': 'Sync Geçmişi',
  '/sync/conflicts': 'Çakışmalar',
  '/notifications': 'Bildirimler',
  '/support': 'Destek',
  '/support/new': 'Yeni Talep',
  '/audit-logs': 'Denetim kayıtları',
  '/analytics': 'Analitik',
  '/accounting': 'Ön Muhasebe Özeti',
  '/accounting/overview': 'Ön Muhasebe Özeti',
  '/invoices': 'Faturalar',
  '/invoices/create': 'Yeni fatura',
  '/reports': 'Raporlar',
  '/migration': 'Geçiş Sihirbazı',
  '/migration/history': 'Geçmiş',
  '/admin': 'Platform İstatistikleri',
  '/admin/organizations': 'Organizasyonlar',
  '/admin/users': 'Kullanıcılar',
  '/admin/partners': 'Partnerler',
  '/admin/partner-link-requests': 'Partner Bağlantıları',
  '/admin/subscriptions': 'Abonelikler',
  '/admin/tickets': 'Destek Talepleri',
  '/admin/audit-logs': 'Denetim kayıtları',
  '/admin/integrations': 'Entegrasyonlar',
  '/partner': 'Müşterilerim',
  '/partner/clients': 'Müşteriler',
  '/partner/commission': 'Komisyon',
  '/partner/commission-report': 'Komisyon raporu',
  '/partner/performance': 'Performans',
  '/partner/onboarding': 'Davetler',
  '/partner/white-label': 'Beyaz etiket',
  '/settings': 'Ayarlar',
  '/settings/partners': 'Partnerler',
  '/settings/profile': 'Profil',
  '/settings/subscription': 'Abonelik',
  '/settings/notifications': 'Bildirim tercihleri',
  '/settings/team': 'Ekip Üyeleri',
  '/settings/webhooks': "Webhook'lar",
  '/settings/organization': 'Organizasyon',
  '/settings/security': 'Güvenlik',
  '/settings/appearance': 'Görünüm',
  '/settings/api-keys': 'API Anahtarları',
  '/settings/accounting-mode': 'Muhasebe Modu',
  '/settings/currency': 'Para Birimi',
  '/settings/invoice-numbering': 'Fatura Numaralama',
  '/settings/erp-sync': 'ERP Senkronizasyon',
  '/settings/product-matching': 'Ürün Eşleştirme',
};

/** Dinamik segment desenleri: regex → üst segment etiketi */
export const BREADCRUMB_DYNAMIC_PARENTS: {
  pattern: RegExp;
  parentPath: string;
  parentLabel: string;
}[] = [
  {
    pattern: /^\/products\/[^/]+$/,
    parentPath: '/products',
    parentLabel: 'Ürünler',
  },
  {
    pattern: /^\/customers\/[^/]+$/,
    parentPath: '/customers',
    parentLabel: 'Müşteriler',
  },
  {
    pattern: /^\/invoices\/create$/,
    parentPath: '/invoices',
    parentLabel: 'Faturalar',
  },
  {
    pattern: /^\/invoices\/[^/]+$/,
    parentPath: '/invoices',
    parentLabel: 'Faturalar',
  },
  {
    pattern: /^\/orders\/[^/]+$/,
    parentPath: '/orders',
    parentLabel: 'Siparişler',
  },
  {
    pattern: /^\/suppliers\/[^/]+$/,
    parentPath: '/suppliers',
    parentLabel: 'Tedarikçiler',
  },
  {
    pattern: /^\/purchase-orders\/[^/]+$/,
    parentPath: '/purchase-orders',
    parentLabel: 'Satın Alma Siparişleri',
  },
  {
    pattern: /^\/connections\/erp\/setup$/,
    parentPath: '/connections',
    parentLabel: 'Bağlantılar',
  },
  {
    pattern: /^\/shipping\/[^/]+$/,
    parentPath: '/shipping',
    parentLabel: 'Kargo',
  },
  {
    pattern: /^\/support\/help\/[^/]+$/,
    parentPath: '/support',
    parentLabel: 'Destek',
  },
  {
    pattern: /^\/support\/[^/]+$/,
    parentPath: '/support',
    parentLabel: 'Destek',
  },
  {
    pattern: /^\/admin\/organizations\/[^/]+$/,
    parentPath: '/admin/organizations',
    parentLabel: 'Organizasyonlar',
  },
  {
    pattern: /^\/admin\/users\/[^/]+$/,
    parentPath: '/admin/users',
    parentLabel: 'Kullanıcılar',
  },
  {
    pattern: /^\/settings\/webhooks\/[^/]+$/,
    parentPath: '/settings/webhooks',
    parentLabel: "Webhook'lar",
  },
];
