-- E-ticaret altyapısı enum değerleri — 2. tur
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'MAGENTO2';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'IDEASOFT';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'WOOCOMMERCE';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'SQUARESPACE';
ALTER TYPE "EcommerceType" ADD VALUE IF NOT EXISTS 'WIX_STORES';
