-- AlterEnum (13. tur — Güneydoğu Asya, Avustralya, Rusya pazaryerleri)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BUKALAPAK';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'JDID';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BLIBLI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TIKI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SENDO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CATCH_AU';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MYDEAL';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TRADEME';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LAMODA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'YANDEX_MARKET';
