-- ERP 5. tur — Avrupa / global muhasebe ve envanter ERP
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'HOLDED';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'DEBITOOR';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'BILLOMAT';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'SEVDESK';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'EXACT_ONLINE';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'TWINFIELD';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'AFAS_ONLINE';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'MONEYBIRD';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'WAVE_ACCOUNTING';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'ZOHO_INVENTORY';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'INFLOW';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'CIN7';
