/** Prisma `OrgType` ile uyumlu */
export type OrgType = 'DIRECT' | 'PARTNER';

/** Prisma `UserRole` ile uyumlu */
export type UserRole =
  | 'SUPER_ADMIN'
  | 'OWNER'
  | 'ADMIN'
  | 'MANAGER'
  | 'VIEWER';

/** Prisma `PlanTier` ile uyumlu */
export type PlanTier = 'BASLANGIC' | 'GELISIM' | 'PRO' | 'KURUMSAL';

/** Prisma `SubStatus` ile uyumlu */
export type SubStatus =
  | 'TRIAL'
  | 'ACTIVE'
  | 'PAUSED'
  | 'CANCELING'
  | 'CANCELLED'
  | 'EXPIRED';

/** Prisma `Marketplace` ile uyumlu */
export type Marketplace =
  | 'TRENDYOL'
  | 'HEPSIBURADA'
  | 'N11'
  | 'AMAZON_TR'
  | 'CICEKSEPETI'
  | 'IDEASOFT'
  | 'PTTAVM'
  | 'PAZARAMA'
  | 'TSOFT'
  | 'TICIMAX'
  | 'WOOCOMMERCE'
  | 'SHOPIFY'
  | 'GETIR'
  | 'GRATIS'
  | 'BOYNER'
  | 'MORHIPO'
  | 'DOLAP'
  | 'EBAY'
  | 'ETSY'
  | 'TEMU'
  | 'SAHIBINDEN'
  | 'MIGROS'
  | 'HEPSIEXPRESS'
  | 'FLO'
  | 'DEFACTO'
  | 'LCWAIKIKI'
  | 'VATAN'
  | 'MEDIAMARKT'
  | 'TEKNOSA'
  | 'KOTON'
  | 'MAVI'
  | 'ALLEGRO'
  | 'WILDBERRIES'
  | 'OZON'
  | 'NOON'
  | 'AMAZON_EU'
  | 'CDISCOUNT'
  | 'KAUFLAND'
  | 'TRENDYOL_GO'
  | 'BANABI'
  | 'A101'
  | 'ELEKTRA'
  | 'ARCELIK'
  | 'VESTEL'
  | 'BIMAKILLI'
  | 'MIGROSHEMEN'
  | 'ROBOMARKT'
  | 'SHOPIGO'
  | 'YEMEKSEPETI'
  | 'GETIR_FOOD'
  | 'TRENDYOL_YEMEK'
  | 'FUUDY'
  | 'MODANISA'
  | 'SEFAMERVE'
  | 'LIDYANA'
  | 'ADDAX'
  | 'VIVENSE'
  | 'CICEKSEPETI_EV'
  | 'EVIDEA'
  | 'PORLAND'
  | 'ALIBABA'
  | 'MADEINCHINA'
  | 'EXPORTIFY'
  | 'GITTIGIDIYOR'
  | 'KITAPYURDU'
  | 'DR'
  | 'SPORTIVE'
  | 'ENPARA'
  | 'LAZADA'
  | 'SHOPEE'
  | 'TOKOPEDIA'
  | 'MEESHO'
  | 'OTTO'
  | 'ZALANDO'
  | 'BOLCOM'
  | 'EMAG'
  | 'IDEALO'
  | 'REALDE'
  | 'ZARA'
  | 'DECATHLON'
  | 'HEPSIBURADA_PREMIUM'
  | 'TRENDYOL_PREMIUM'
  | 'PAZARAMA_PREMIUM'
  | 'N11_PRO'
  | 'AMAZON_AE'
  | 'NAMSHI'
  | 'CARREFOUR_ME'
  | 'JUMIA'
  | 'DARAZ'
  | 'FLIPKART'
  | 'SNAPDEAL'
  | 'MYNTRA'
  | 'RAKUTEN'
  | 'QOO10'
  | 'LAZADA_PH'
  | 'MERCADOLIBRE'
  | 'GETIR_YEMEK'
  | 'LETGO'
  | 'SAHIBINDEN_PRO'
  | 'SHOPIVERSE'
  | 'WALMART'
  | 'TARGET_PLUS'
  | 'BESTBUY'
  | 'WAYFAIR'
  | 'OVERSTOCK'
  | 'FNAC'
  | 'LAREDOUTE'
  | 'SPARTOO'
  | 'MANOMANO'
  | 'VEEPEE'
  | 'TRENDYOL_INT'
  | 'MIGROS_SANAL'
  | 'CARREFOURSA'
  | 'BIM_ONLINE'
  | 'SOK_MARKET'
  | 'TAZE_DIREKT'
  | 'GORILLAS'
  | 'INSTACART'
  | 'ALIBABA_TR'
  | 'TRENDYOL_MILLA'
  | 'SAHIBINDEN_PREMIUM'
  | 'BUKALAPAK'
  | 'JDID'
  | 'BLIBLI'
  | 'TIKI'
  | 'SENDO'
  | 'CATCH_AU'
  | 'MYDEAL'
  | 'TRADEME'
  | 'LAMODA'
  | 'YANDEX_MARKET'
  | 'TAKEALOT'
  | 'BIDORBUY'
  | 'KILIMALL'
  | 'KONGA'
  | 'SOUQ'
  | 'SHARAF_DG'
  | 'WADI'
  | 'OPENSOOQ'
  | 'CIMRI';

/** Prisma `ErpType` ile uyumlu */
export type ErpType =
  | 'BIZIMHESAP'
  | 'PARASUT'
  | 'TSOFT'
  | 'TICIMAX'
  | 'LOGO'
  | 'MIKRO'
  | 'LUCA'
  | 'NETSIS'
  | 'ETA'
  | 'KOLAYBI'
  | 'ZIRVE'
  | 'NEBIM'
  | 'EBA'
  | 'SAP_B1'
  | 'ISNET'
  | 'MYSOFT'
  | 'PROTEL'
  | 'SIMPRA'
  | 'LOGO_COMMERCE'
  | 'BIZIM_MUHASEBE'
  | 'LOGO_CLOUD'
  | 'FINANS_MUHASEBE'
  | 'MIKRO_BULUT';

/** Prisma `EcommerceType` ile uyumlu */
export type EcommerceType =
  | 'TICIMAX'
  | 'TSOFT'
  | 'MAGENTO'
  | 'PRESTASHOP'
  | 'OPENCART'
  | 'FAPRIKA'
  | 'UNIPOS'
  | 'AKINON'
  | 'IKAS'
  | 'SHOPIVERSE'
  | 'SHOPIROLL'
  | 'MEDUSA'
  | 'VENDURE'
  | 'SALEOR'
  | 'IYZICO'
  | 'STRIPE';

/** Prisma `CargoProvider` ile uyumlu */
export type CargoProvider =
  | 'YURTICI'
  | 'ARAS'
  | 'MNG'
  | 'SURAT'
  | 'PTT'
  | 'PTT_KARGO'
  | 'UPS'
  | 'DHL'
  | 'DHL_PARCEL'
  | 'FEDEX'
  | 'SENDEO'
  | 'HEPSIJET'
  | 'TRENDYOL_EXPRESS'
  | 'NETLOG'
  | 'HOROZ'
  | 'TNT'
  | 'GLS'
  | 'DPD'
  | 'HERMES'
  | 'POSTNL'
  | 'BRINGO'
  | 'CEVA'
  | 'NART_KARGO'
  | 'KOLAY_GELSIN';

/** Prisma `PartnerStatus` ile uyumlu */
export type PartnerStatus = 'ACTIVE' | 'PAUSED' | 'TERMINATED';

/** Prisma `CommissionStatus` ile uyumlu */
export type CommissionStatus = 'PENDING' | 'PAID' | 'CANCELLED';

/** Prisma `SyncDirection` ile uyumlu */
export type SyncDirection = 'PUSH' | 'PULL';
