-- AlterEnum (39. tur — Orta Asya, Ortadoğu BNPL, Afrika, küresel niş)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ZOOD';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MEGATRADE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MARKET_KZ';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ARBUZ_KZ';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TAMARA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TABBY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CASHI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TAMTAM';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'JUMIA_ET';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AUCHAN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LEROY_MERLIN';
