-- AlterEnum (14. tur — Afrika & Orta Doğu pazaryerleri)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TAKEALOT';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BIDORBUY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KILIMALL';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KONGA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SOUQ';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SHARAF_DG';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'WADI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'OPENSOOQ';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CIMRI';
