-- AlterEnum (29. tur — ev & yaşam, mobilya, dekorasyon, bahçe & outdoor)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'HOUZZ';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MADE_COM';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ARTICLE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'JOSS_MAIN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BIRCH_LANE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PERIGOLD';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KARACA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MADAME_COCO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ENGLISH_HOME';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LINENS_N_THINGS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GARDENA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'OBI_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BAUHAUS_TR';
