-- AlterEnum (36. tur — Doğu Avrupa, Balkan, Rusya & BDT)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'FAVI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LIMUNDO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'KUPUJEM_PRODAJEM';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'NJUSKALO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'OLX_PL';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ALIEXPRESS_RU';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AVITO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SBERMARKET';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'PAZARUVAJ';
