-- ERP 6. tur — Türk muhasebe, perakende POS, üretim & tedarik ERP
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'FINNET';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'ETAX';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'UYUMSOFT';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'EDUSON';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'SMARTIKS';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'POSEIDON_POS';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'RESTMAN';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'SIMPRA_PLUS';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'AKINON_ERP';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'BIMEKS_ERP';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'MRPEASY';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'KATANA_MRP';
