-- AlterEnum (25. tur — B2B global/Türkiye, dropshipping)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ALIBABA_B2B';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'GLOBAL_SOURCES';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'DHGATE';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'INDIAMART';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TRADEINDIA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'EC21';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TEDARIKCI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BUYUK_MAGAZA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TOPTANEVI';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SAHIBINDEN_B2B';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SPOCKET';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'OBERLO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'AUTODS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'DOBA';
