-- AlterEnum (31. tur — Orta Doğu & Afrika genişletme)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SHUKRAN';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'BRANDS4LESS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'HARAJ';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ZANDO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'MEQASA';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'VENDTEK';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'SHOPANDSEND';
