-- ERP 4. tur — Türk muhasebe / e-ticaret ERP ve global muhasebe
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'ZIRVE_BULUT';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'MIKRO_ERP';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'ISBIR_ERP';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'ALICI_ERP';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'HIZLI_MUHASEBE';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'IDEASOFT_ERP';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'VETASSOFT';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'PROBIL';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'ETRADE_ERP';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'ZOHO_BOOKS';
ALTER TYPE "ErpType" ADD VALUE IF NOT EXISTS 'FRESHBOOKS';
