-- AlterEnum (26. tur — gıda, sağlık, güzellik)
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'CULT_BEAUTY';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'LOOKFANTASTIC';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'NOTINO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'IHERB';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'VITACOST';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'HELLOFRESH';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'DELIVEROO';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'UBER_EATS';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'ROSSMANN_TR';
ALTER TYPE "Marketplace" ADD VALUE IF NOT EXISTS 'TRENDYOL_GROCERIES';
